version: 2
updates:
  - package-ecosystem: npm
    directory: /api
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Kathmandu
    open-pull-requests-limit: 5
    groups:
      production-patches:
        dependency-type: production
        update-types:
          - patch
      development-patches:
        dependency-type: development
        update-types:
          - patch

  - package-ecosystem: npm
    directory: /next-zeo
    schedule:
      interval: weekly
      day: monday
      time: "03:15"
      timezone: Asia/Kathmandu
    open-pull-requests-limit: 5
    groups:
      production-patches:
        dependency-type: production
        update-types:
          - patch
      development-patches:
        dependency-type: development
        update-types:
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Kathmandu
    open-pull-requests-limit: 5
